# Generated by Django 3.2.8 on 2023-06-28 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classNumber', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('SSN', models.BigAutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('0', 'female'), ('1', 'male')], max_length=200)),
                ('address', models.TextField()),
                ('familyName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='managing.person')),
                ('contract_type', models.CharField(choices=[('a', 'hourly'), ('b', 'contractly')], max_length=200)),
                ('contract_salary', models.IntegerField()),
                ('contract_number', models.IntegerField(unique=True)),
                ('degree', models.CharField(max_length=200)),
            ],
            bases=('managing.person',),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('childID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('familyName', models.CharField(max_length=200)),
                ('hobbies', models.CharField(blank=True, max_length=200, null=True)),
                ('birthDate', models.DateTimeField(auto_now_add=True)),
                ('classes', models.ManyToManyField(to='managing.Class')),
                ('parents', models.ManyToManyField(to='managing.Person')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(to='managing.Teacher'),
        ),
    ]
